name: Build, Test, Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Pack
      run: dotnet pack M0glan.Sqlite.Encryption/M0glan.Sqlite.Encryption.csproj -c Release
    - name: Prepare
      run: dotnet nuget add source --username m0glan --password ${{secrets.GITHUB_TOKEN}} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/m0glan/index.json"
    - name: Publish
      run: dotnet nuget push M0glan.Sqlite.Encryption/bin/Release/*.nupkg --api-key ${{secrets.GITHUB_TOKEN}}  --source "github"
